export const courses = [
  {
    id: 1,
    title: "Big 4 Auditor Financial Analyst",
    description: "Mulai transformasi dengan instruktur profesional, harga yang terjangkau, dan kurikulum terbaik",
    category: "bisnis",
    thumbImage: "https://picsum.photos/500/300?random=1",
    instructor: {
      name: "Jenna Ortega",
      role: "Senior Accountant",
      company: "Gojek",
      image: "https://i.pravatar.cc/300?img=1",
    },
    rating: 3.5,
    totalReviews: 86,
    price: 300000,
  },
  {
    id: 2,
    title: "Digital Marketing Mastery",
    description: "Kuasai strategi pemasaran digital dari ahlinya, mulai dari SEO hingga social media ads",
    category: "pemasaran",
    thumbImage: "https://picsum.photos/500/300?random=2",
    instructor: {
      name: "Andi Pratama",
      role: "Marketing Manager",
      company: "Tokopedia",
      image: "https://i.pravatar.cc/300?img=2",
    },
    rating: 4.5,
    totalReviews: 124,
    price: 250000,
  },
  {
    id: 3,
    title: "UI/UX Design Fundamentals",
    description: "Pelajari prinsip desain modern dan buat produk yang disukai pengguna",
    category: "desain",
    thumbImage: "https://picsum.photos/500/300?random=3",
    instructor: {
      name: "Sarah Wijaya",
      role: "Lead Designer",
      company: "Shopee",
      image: "https://i.pravatar.cc/300?img=3",
    },
    rating: 5,
    totalReviews: 210,
    price: 199000,
  },
  {
    id: 4,
    title: "Public Speaking & Komunikasi Efektif",
    description: "Tingkatkan kepercayaan diri dan kemampuan berbicara di depan umum secara profesional",
    category: "pengembangan diri",
    thumbImage: "https://picsum.photos/500/300?random=4",
    instructor: {
      name: "Budi Santoso",
      role: "Corporate Trainer",
      company: "Traveloka",
      image: "https://i.pravatar.cc/300?img=4",
    },
    rating: 4,
    totalReviews: 98,
    price: 175000,
  },
  {
    id: 5,
    title: "Strategi Bisnis & Entrepreneurship",
    description: "Bangun bisnis dari nol dengan strategi yang terbukti dari para entrepreneur sukses",
    category: "bisnis",
    thumbImage: "https://picsum.photos/500/300?random=5",
    instructor: {
      name: "Rina Kusuma",
      role: "Business Consultant",
      company: "McKinsey",
      image: "https://i.pravatar.cc/300?img=5",
    },
    rating: 4.5,
    totalReviews: 175,
    price: 350000,
  },
  {
    id: 6,
    title: "Graphic Design dengan Figma",
    description: "Dari pemula hingga mahir, kuasai Figma untuk kebutuhan desain profesional",
    category: "desain",
    thumbImage: "https://picsum.photos/500/300?random=6",
    instructor: {
      name: "Kevin Lie",
      role: "Senior UI Designer",
      company: "Bukalapak",
      image: "https://i.pravatar.cc/300?img=6",
    },
    rating: 3.5,
    totalReviews: 63,
    price: 225000,
  },
  {
    id: 7,
    title: "Social Media Marketing Strategy",
    description: "Optimalkan brand kamu di Instagram, TikTok, dan LinkedIn untuk hasil maksimal",
    category: "pemasaran",
    thumbImage: "https://picsum.photos/500/300?random=7",
    instructor: {
      name: "Dina Marlina",
      role: "Social Media Strategist",
      company: "Grab",
      image: "https://i.pravatar.cc/300?img=7",
    },
    rating: 4,
    totalReviews: 141,
    price: 180000,
  },
  {
    id: 8,
    title: "Mindset & Produktivitas Kerja",
    description: "Ubah kebiasaan dan pola pikir untuk mencapai performa terbaik dalam karier",
    category: "pengembangan diri",
    thumbImage: "https://picsum.photos/500/300?random=8",
    instructor: {
      name: "Fajar Nugroho",
      role: "Life Coach",
      company: "Freelance",
      image: "https://i.pravatar.cc/300?img=8",
    },
    rating: 5,
    totalReviews: 302,
    price: 150000,
  },
  {
    id: 9,
    title: "Brand Identity & Visual Storytelling",
    description: "Ciptakan identitas brand yang kuat dan berkesan melalui visual yang konsisten dan profesional",
    category: "desain",
    thumbImage: "https://picsum.photos/500/300?random=9",
    instructor: {
      name: "Ayu Rahmawati",
      role: "Creative Director",
      company: "Tiket.com",
      image: "https://i.pravatar.cc/300?img=0",
    },
    rating: 4.5,
    totalReviews: 189,
    price: 275000,
  },
]