import type { Metadata } from "next";
import { Geist, Geist_Mono, DM_Sans, Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "../features/navbar";
import { AuthProvider } from "../context/AuthContext";
import { Toaster } from "sonner";
import { CourseProvider } from "../context/CourseContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const DMSans = DM_Sans({
  variable: "--font-dm-sans",
  subsets: ["latin"],
});

const poppins = Poppins({
  variable: "--font-poppins",
  weight: ["400"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Video Belajar",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${DMSans.variable} ${poppins.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <AuthProvider>
          <CourseProvider>
            <Toaster richColors={true} position="top-center" />
            <Navbar />
            {children}
          </CourseProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
